src/app/servicesModule/services/create-poll-storage.service.ts, src/app/voting/views/vote-in-poll/vote-in-poll.component.ts, src/environments/environment.prod.ts, src/environments/environment.ts
1. Add new endpoint for voting storage
2. Add  new endpoint for apostille QR
=> New endpoints 

src/environments/environment.main.ts
Add  environment config storage  connection unload
=> add new  environment config storage 

src/app/voting/views/vote-in-poll/vote-in-poll.component.ts
- Fixed vote counting with more than 1 page of transactions
=> fix: vote result counting

src/app/accounts/accounts-routing.module.ts, src/app/accounts/accounts.module.ts, src/app/accounts/views/delegate/delegate.component.css, src/app/accounts/views/delegate/delegate.component.html, src/app/accounts/views/delegate/delegate.component.spec.ts, src/app/accounts/views/delegate/delegate.component.ts, src/app/config/app.config.ts, src/app/servicesModule/views/services-box/services-box.component.ts, src/app/shared/services/proximax.provider.ts, src/app/transactions/services/transactions.service.ts
- unlink and unlink account
- restrict feature if it is multisig account
=> added delegate feature

src/app/accounts/views/delegate/delegate.component.html, src/app/accounts/views/delegate/delegate.component.ts
- update delegate UI
- enable new account or existing account linking
=> update delegate account selection

package-lock.json, package.json, src/app/apostille/services/audit-apostille-verifier.ts, src/app/apostille/views/audit-apostille/audit-apistille-verifier.ts, src/app/apostille/views/create-apostille/create-apostille.component.ts, src/app/shared/services/proximax.provider.ts, src/app/wallet/services/wallet.service.ts
- remove js-xpx-chain-library dependency
- use KeyPair, Crypto and Convert from tsjs-xpx-chain-sdk instead
=> remove js-xpx-chain-library dependency, use tsjs-xpx-chain-sdk instead

src/app/home/views/home/home.component.ts, src/app/shared/services/proximax.provider.ts, src/app/wallet/services/wallet.service.ts, src/app/wallet/views/selection-wallet-creation-type/selection-wallet-creation-type.component.ts
- use the wallet algorithm enum from tsjs-xpx-chain-sdk
=> update wallet algorithm

src/app/voting/views/polls/polls.component.html, src/app/voting/views/vote-in-poll/vote-in-poll.component.html, src/app/voting/views/vote-in-poll/vote-in-poll.component.ts
- UI and flow will have issue when closing the modal while calculating the statistic
- fix issue of sometime unable to get poll id (use paramMap.subscribe to get poll id)
- disable refresh button when loading vote list
=> fix issue in vote result when click close modal

src/environments/environment.main.ts, src/environments/environment.prod.ts, src/environments/environment.ts
**Update**
- Multisig-multilevel
**Fix bug**
- Account
**Features**
- Parcial
- Trasfer
=> Multisig multilevel

src/app/servicesModule/services/create-poll-storage.service.ts, src/app/voting/views/polls/polls.component.html, src/app/voting/views/polls/polls.component.ts, src/app/voting/views/vote-in-poll/vote-in-poll.component.ts
* fix poll results details loading, fix progress bar
=> fix poll results details loading, fix progress bar

src/app/dashboard/components/transfer-type-bonded/transfer-type-bonded.component.html, src/app/dashboard/components/transfer-type-bonded/transfer-type-bonded.component.ts, src/app/dashboard/components/transfer-type/transfer-type.component.html, src/app/dashboard/components/transfer-type/transfer-type.component.ts
- recipient able to decrypt message with local public key
- sender will be prompt for recipient public key if not found from blockchain when trying to decrypt message
=> fix encrypted message handling - recipient public key missing

src/app/dashboard/components/transfer-type-bonded/transfer-type-bonded.component.ts, src/app/dashboard/views/dashboard/dashboard.component.ts
- fix dashboard sorting of confirmed transaction based on block height
=> fix dashboard sorting

src/app/dashboard/services/dashboard.service.ts, src/app/dashboard/views/dashboard/dashboard.component.html, src/app/dashboard/views/dashboard/dashboard.component.ts, src/app/transactions/services/transactions.service.ts, src/assets/configuration.js, src/assets/configuration.mainnet.js, src/assets/configuration.testnet.js
- add block height to dashboard confirmed transaction
- add local storage of block timestamp
=> display block height of confirmed tx, save block timestamp

src/app/accounts/views/alias-address-to-namespace/alias-address-to-namespace.component.ts, src/app/mosaics/views/alias-mosaics-to-namespace/alias-mosaics-to-namespace.component.ts, src/app/storage/views/upload-file/upload-file.component.ts, src/app/transactions/views/create-transfer/create-transfer.component.ts
- Link error and unlink namespace
> 1. link namespace to mosaics
> 2. link namespace to account
- Mosaic creation error
- Validate address in tx trasfer
- Change options encryption methods ipfs
=> Fix bug/task

src/app/dashboard/views/dashboard/dashboard.component.ts, src/app/servicesModule/services/create-poll-storage.service.ts, src/app/voting/views/create-poll/create-poll.component.ts, src/app/voting/views/polls/polls.component.ts, src/app/voting/views/vote-in-poll/vote-in-poll.component.ts
- fix blank screen when voting with whitelist setting
- fixed error on certificate saving
=> fix vote whitelist and vote certificate

src/app/namespace/views/extend-duration-namespace/extend-duration-namespace.component.html, src/app/voting/views/polls/polls.component.html, src/app/voting/views/vote-in-poll/vote-in-poll.component.html
=> replace text

src/app/dashboard/services/dashboard.service.ts, src/app/dashboard/views/dashboard/dashboard.component.css, src/app/dashboard/views/dashboard/dashboard.component.html, src/app/dashboard/views/dashboard/dashboard.component.ts, src/app/servicesModule/services/namespaces.service.ts
- added namespace and mosaic info at dashboard
=> added namespace and mosaic info at dashboard

src/app/dashboard/views/dashboard/dashboard.component.ts
- fix dashboard variable checking
=> fix dashboard checking

src/app/dashboard/views/dashboard/dashboard.component.ts
- fix error when logout at dashboard
=> fix error when logout

src/app/mosaics/views/mosaics-supply-change/mosaics-supply-change.component.html, src/app/mosaics/views/mosaics-supply-change/mosaics-supply-change.component.ts
- different message will display when no mosaic and no supply mutable mosaic found
=> update msg when no supplyMutable mosaic found

src/app/apostille/services/apostille.service.ts, src/app/apostille/views/create-apostille/create-apostille.component.html, src/app/apostille/views/create-apostille/create-apostille.component.ts, src/app/mosaics/views/mosaics-supply-change/mosaics-supply-change.component.html, src/app/mosaics/views/mosaics-supply-change/mosaics-supply-change.component.ts, src/app/multi-sign/views/edit-account-multisig/edit-account-multisig.component.ts, src/app/storage/views/my-file/my-file.component.ts, src/app/storage/views/upload-file/upload-file.component.html, src/app/storage/views/upload-file/upload-file.component.ts, src/assets/configuration.js, src/assets/configuration.mainnet.js, src/assets/configuration.testnet.js
<h2>Update</h2>
<ul>
<h3>Setting</h3>
<li>New version 0.5.7</li>
<li>Enabled storage module for developer</li>
</ul>
<h2>Text correction</h2>
<ul>
<h3>Edit multisig</h3>
<li>Cosignee / cosigner</li>
<h3>Storage</h3>
<li>Timestand / Date</li>
</ul>
<h2>Bug/features</h2>
<ul>
<h3>Mosaic supply</h3>
<li>Validation text is added if supply quantity is 0</li>
<h3>Apostille</h3>
<li>Remove required tags in apostille</li>
<h3>Storage</h3>
<li>Validate select encryption method</li>
<li>Next button validate "disable"</li>
</ul>
=> Fix bug/attestation storage

src/app/storage/views/my-file/my-file.component.html, src/app/storage/views/my-file/my-file.component.ts
=> validate button loading

src/app/dashboard/views/dashboard/dashboard.component.ts, src/app/transactions/views/partial/partial.component.ts
<h2>Update</h2>
<ul>
<h3>Partial</h3>
<li>Date format</li>
</ul>
=> date format in partial
